# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pointnet2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pointnet2.proto',
  package='pointnet2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fpointnet2.proto\x12\tpointnet2\"\x1f\n\x0cPointRequest\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\"\x1d\n\nPointReply\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\x32H\n\x05Point\x12?\n\x07Segment\x12\x17.pointnet2.PointRequest\x1a\x15.pointnet2.PointReply\"\x00(\x01\x30\x01\x62\x06proto3'
)




_POINTREQUEST = _descriptor.Descriptor(
  name='PointRequest',
  full_name='pointnet2.PointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray', full_name='pointnet2.PointRequest.ndarray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=61,
)


_POINTREPLY = _descriptor.Descriptor(
  name='PointReply',
  full_name='pointnet2.PointReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray', full_name='pointnet2.PointReply.ndarray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['PointRequest'] = _POINTREQUEST
DESCRIPTOR.message_types_by_name['PointReply'] = _POINTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointRequest = _reflection.GeneratedProtocolMessageType('PointRequest', (_message.Message,), {
  'DESCRIPTOR' : _POINTREQUEST,
  '__module__' : 'pointnet2_pb2'
  # @@protoc_insertion_point(class_scope:pointnet2.PointRequest)
  })
_sym_db.RegisterMessage(PointRequest)

PointReply = _reflection.GeneratedProtocolMessageType('PointReply', (_message.Message,), {
  'DESCRIPTOR' : _POINTREPLY,
  '__module__' : 'pointnet2_pb2'
  # @@protoc_insertion_point(class_scope:pointnet2.PointReply)
  })
_sym_db.RegisterMessage(PointReply)



_POINT = _descriptor.ServiceDescriptor(
  name='Point',
  full_name='pointnet2.Point',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='Segment',
    full_name='pointnet2.Point.Segment',
    index=0,
    containing_service=None,
    input_type=_POINTREQUEST,
    output_type=_POINTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POINT)

DESCRIPTOR.services_by_name['Point'] = _POINT

# @@protoc_insertion_point(module_scope)
